import { Component, OnInit ,HostListener} from '@angular/core';

@Component({
  selector: 'app-driverdashboard',
  templateUrl: './driverdashboard.component.html',
  styleUrls: ['./driverdashboard.component.scss']
})
export class DriverdashboardComponent implements OnInit{

  public dashboardData :any=[
    {
      companyid:"1",
      companyname:"company A",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 14",
          vehiclename:"00-0014",
          routename:"route 14",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:04",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:20,          
          header : "row H2030",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 15",
          vehiclename:"00-0015",
          routename:"route 15",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:05",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:40,          
          header : "row H4030",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-nonpass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-pass",          
        },
        {
          drivername:"driver 16",
          vehiclename:"00-0016",
          routename:"route 16",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:06",
          speed:0,
          vstatus:80,          
          vstatusname:"GPS Lost",
          vcolor:"#C0C0C0",          
          dstatus:40,          
          header : "row H4080",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    },
    {
      companyid:"2",
      companyname:"company B",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    },
    {
      companyid:"3",
      companyname:"company C",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 13",
          vehiclename:"00-0013",
          routename:"route 13",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:03",
          speed:0,
          vstatus:31,          
          vstatusname:"จอดติดเครื่อง",
          vcolor:"#DAA520",          
          dstatus:20,          
          header : "row H2031",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",        
        },
        {
          drivername:"driver 14",
          vehiclename:"00-0014",
          routename:"route 14",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:04",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:20,          
          header : "row H2030",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 15",
          vehiclename:"00-0015",
          routename:"route 15",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:05",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:40,          
          header : "row H4030",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 16",
          vehiclename:"00-0016",
          routename:"route 16",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:06",
          speed:0,
          vstatus:80,          
          vstatusname:"GPS Lost",
          vcolor:"#C0C0C0",          
          dstatus:40,          
          header : "row H4080",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]
    },
    {
      companyid:"4",
      companyname:"company E",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 11",
          vehiclename:"00-0011",
          routename:"route 11",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:00",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:10,          
          header : "row H1033",   
          ontheway:"icon-normal",
          dstatusname:"รอยืนยัน",
          dcolor:"#FF0000",          
          wakeuptaget:"06:00",
          wakeuptime:"00:00",
          wakeupstatus:0,
          wakeupicon:"icon-nonpass",
          starttaget:"06:30",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 12",
          vehiclename:"00-0012",
          routename:"route 12",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"60:01",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:20,          
          header : "row H2033",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:35",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal", 
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 13",
          vehiclename:"00-0013",
          routename:"route 13",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:03",
          speed:0,
          vstatus:31,          
          vstatusname:"จอดติดเครื่อง",
          vcolor:"#DAA520",          
          dstatus:20,          
          header : "row H2031",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",        
        },
        {
          drivername:"driver 14",
          vehiclename:"00-0014",
          routename:"route 14",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:04",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:20,          
          header : "row H2030",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 15",
          vehiclename:"00-0015",
          routename:"route 15",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:05",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:40,          
          header : "row H4030",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 16",
          vehiclename:"00-0016",
          routename:"route 16",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:06",
          speed:0,
          vstatus:80,          
          vstatusname:"GPS Lost",
          vcolor:"#C0C0C0",          
          dstatus:40,          
          header : "row H4080",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    },
    {
      companyid:"5",
      companyname:"company F",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    },
    {
      companyid:"6",
      companyname:"company G",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 11",
          vehiclename:"00-0011",
          routename:"route 11",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:00",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:10,          
          header : "row H1033",   
          ontheway:"icon-normal",
          dstatusname:"รอยืนยัน",
          dcolor:"#FF0000",          
          wakeuptaget:"06:00",
          wakeuptime:"00:00",
          wakeupstatus:0,
          wakeupicon:"icon-nonpass",
          starttaget:"06:30",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 12",
          vehiclename:"00-0012",
          routename:"route 12",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"60:01",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:20,          
          header : "row H2033",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:35",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal", 
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 13",
          vehiclename:"00-0013",
          routename:"route 13",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:03",
          speed:0,
          vstatus:31,          
          vstatusname:"จอดติดเครื่อง",
          vcolor:"#DAA520",          
          dstatus:20,          
          header : "row H2031",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",        
        },
        {
          drivername:"driver 14",
          vehiclename:"00-0014",
          routename:"route 14",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:04",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:20,          
          header : "row H2030",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 15",
          vehiclename:"00-0015",
          routename:"route 15",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:05",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:40,          
          header : "row H4030",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 16",
          vehiclename:"00-0016",
          routename:"route 16",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:06",
          speed:0,
          vstatus:80,          
          vstatusname:"GPS Lost",
          vcolor:"#C0C0C0",          
          dstatus:40,          
          header : "row H4080",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    },
    {
      companyid:"7",
      companyname:"company H",
      totalwakeup:0,
      totalalgohol:0,
      totaltemp:0,
      totalstart:0,
      totalontheway:0,
      totalfinish:0,
      listdriver:[
        {
          drivername:"driver 11",
          vehiclename:"00-0011",
          routename:"route 11",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:00",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:10,          
          header : "row H1033",   
          ontheway:"icon-normal",
          dstatusname:"รอยืนยัน",
          dcolor:"#FF0000",          
          wakeuptaget:"06:00",
          wakeuptime:"00:00",
          wakeupstatus:0,
          wakeupicon:"icon-nonpass",
          starttaget:"06:30",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 12",
          vehiclename:"00-0012",
          routename:"route 12",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"60:01",
          speed:0,
          vstatus:33,          
          vstatusname:"จอด",
          vcolor:"#FF0000",          
          dstatus:20,          
          header : "row H2033",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:35",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal", 
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",
        },
        {
          drivername:"driver 13",
          vehiclename:"00-0013",
          routename:"route 13",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:03",
          speed:0,
          vstatus:31,          
          vstatusname:"จอดติดเครื่อง",
          vcolor:"#DAA520",          
          dstatus:20,          
          header : "row H2031",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"00:00",
          startstatus:0,
          starticon:"icon-nonpass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"00:00",
          endpoint:"00:00",        
        },
        {
          drivername:"driver 14",
          vehiclename:"00-0014",
          routename:"route 14",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:04",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:20,          
          header : "row H2030",   
          ontheway:"icon-normal",
          dstatusname:"ยืนยัน",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"00:00",
          algohallevel:0,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 15",
          vehiclename:"00-0015",
          routename:"route 15",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:05",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:40,          
          header : "row H4030",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 16",
          vehiclename:"00-0016",
          routename:"route 16",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:06",
          speed:0,
          vstatus:80,          
          vstatusname:"GPS Lost",
          vcolor:"#C0C0C0",          
          dstatus:40,          
          header : "row H4080",   
          ontheway:"icon-normal",
          dstatusname:"ออกเดินทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",          
        },
        {
          drivername:"driver 17",
          vehiclename:"00-0017",
          routename:"route 17",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030",   
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 18",
          vehiclename:"00-0018",
          routename:"route 18",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:08",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:52,
          algohalstatus:0,
          algohalicon:"icon-nonpass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 19",
          vehiclename:"00-0019",
          routename:"route 19",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          ontheway:"icon-pass",
          header : "row H5041", 
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 20",
          vehiclename:"00-0020",
          routename:"route 20",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 21",
          vehiclename:"00-0021",
          routename:"route 21",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:09",
          speed:0,
          vstatus:41,          
          vstatusname:"ความเร็วเกิน",
          vcolor:"#D308F5",          
          dstatus:50,          
          header : "row H5041", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 22",
          vehiclename:"00-0022",
          routename:"route 22",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 23",
          vehiclename:"00-0023",
          routename:"route 23",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
        {
          drivername:"driver 24",
          vehiclename:"00-0024",
          routename:"route 24",
          location:"ตำบล.... อำเภอ.... จังหวัด...",
          lastupdate:"06:07",
          speed:0,
          vstatus:30,          
          vstatusname:"เดินทาง",
          vcolor:"#008000",          
          dstatus:50,          
          header : "row H5030", 
          ontheway:"icon-pass",
          dstatusname:"อยู่ในเส้นทาง",
          dcolor:"#FF4500",          
          wakeuptaget:"05:30",
          wakeuptime:"05:25",
          wakeupstatus:1,
          wakeupicon:"icon-pass",
          starttaget:"06:00",
          starttime:"05:50",
          startstatus:1,
          starticon:"icon-pass",
          algohaltime:"05:40",
          algohallevel:0,
          algohalstatus:1,
          algohalicon:"icon-pass",
          temptime:"00:00",
          templevel:0,
          tempstatus:0,
          tempicon:"icon-normal",
          tagetfistpoint:"06:30",
          tagetendpoint:"07:30",
          fistpoint:"06:29",
          endpoint:"00:00",
        },
      ]

    }
  ]
  public show = 1;
  
  public isDesktop = 5;
  public listdriver :any;

  @HostListener('window:resize', ['$event'])




  ngOnInit(): void {

    this.dashboardData.forEach((item: any) => {
      item.totalwakeup=item.listdriver.reduce((sum: any, item: { wakeupstatus: any; }) => sum + item.wakeupstatus, 0);
      item.totalalgohol=item.listdriver.reduce((sum: any, item: { algohalstatus: any; }) => sum + item.algohalstatus, 0);
      item.totaltemp=item.listdriver.reduce((sum: any, item: { tempstatus: any; }) => sum + item.tempstatus, 0);
      item.totalstart=item.listdriver.reduce((sum: any, item: { startstatus: any; }) => sum + item.startstatus, 0);
      // console.log("item : ",item); 
    });

    // var sum = this.dashboardData.reduce((acc:any, obj:any) => acc + obj.value, 0);
    // console.log(sum); 
    // totalwakeup:0,
    // totalalgohol:0,
    // totaltemp:0,
    // totalstart:0,
    // totalontheway:0,
    // totalfinish:0,

    this.onResize(window); 
    this.listdriver = this.dashboardData[0].listdriver;
  }
  
  onResize(event: any) {
    // console.log('Window resized!', event.screen.width);
    if (event.screen.width <= 1024) { this.isDesktop = 1; } 
    else { this.isDesktop = 5;}
  }

  toggleDetails(driver: any) {
    driver.showDetails = !driver.showDetails;
  }

}
