import { Component, OnInit,ViewChild} from '@angular/core';
import { MatTableDataSource} from '@angular/material/table';
import {MatSort} from '@angular/material/sort';
import {MatPaginator} from '@angular/material/paginator';
import {PlanmasterModel} from './searchplanmasterpage.module';

@Component({
  selector: 'app-searchplanmasterpage',
  templateUrl: './searchplanmasterpage.component.html',
  styleUrls: ['./searchplanmasterpage.component.scss']
})

export class SearchplanmasterpageComponent implements OnInit{
  constructor() {}
  public mainData : PlanmasterModel[] = []; 
  public displayedColumns: string[] =[];
  public displayedColumnsData: string[] =[]  ;
  // public  dataSource = new MatTableDataSource(this.mainData); 
  public  dataSource = new MatTableDataSource(this.mainData); 
  @ViewChild(MatSort) sort!: MatSort;
  @ViewChild(MatPaginator) paginator!: MatPaginator;

  ngOnInit(): void {
    
  }
  ngAfterViewInit() {
    this.setData();    
  }
  onSelectedRow(row:any){
    // console.log(row);
  }

  applyFilter(event:any){
    var filterValue = event.value;
    this.dataSource.filter = filterValue.trim().toLocaleLowerCase();
  }


  async setData(){
    this.displayedColumns = ['company','shipname','roundname','routename','item','vname','vlicense','provincename','driverfullname','phone','mobile','linename','lineimage','nickname','drivername','surname','dlicensname','dlicense','dlicensetype','province','provincecode','round','planid','compid','routeid','shipid','vehicleid','vtypename','transtatus'];
    // this.displayedColumnsData = ['company','routename','totaltrip','totalship0','totalship1','id','compid'];
    this.mainData = await  this.getData();
    this.dataSource = new MatTableDataSource(this.mainData); 
    this.dataSource.sort = this.sort;
    this.dataSource.paginator = this.paginator;

  }

  async getData(){
    return [
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายLG - คลองกล่ำ",item: 1,vname: "นค-807 ระยอง",vlicense: "นค-807",provincename: "ระยอง",driverfullname: "สิงชัย 098-826-1037",phone: "098-826-1037",mobile: "0988261037",linename: "",lineimage: "",nickname: "",drivername: "จตุรพล",surname: "สิงชัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 65,compid: 1,routeid: 30,shipid: 0,vehicleid: 82,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายจุกกะเฌอ - คอนโดบ่อวิน",item: 1,vname: "ก-2292 กรุงเทพมหานคร",vlicense: "ก-2292",provincename: "กรุงเทพมหานคร",driverfullname: "หามนตรี 081-973-3746",phone: "081-973-3746",mobile: "0819733746",linename: "",lineimage: "",nickname: "",drivername: "นิเรศ",surname: "หามนตรี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 74,compid: 1,routeid: 31,shipid: 0,vehicleid: 71,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายจุกกะเฌอ - คอนโดบ่อวิน",item: 2,vname: "ข-5347 ชลบุรี",vlicense: "ข-5347",provincename: "ชลบุรี",driverfullname: "สุขอู๊ด 061-849-7300",phone: "061-849-7300",mobile: "0618497300",linename: "",lineimage: "",nickname: "",drivername: "สุนันทา",surname: "สุขอู๊ด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 68,compid: 1,routeid: 31,shipid: 0,vehicleid: 76,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายชลบุรี - ดอนหัวฬ่อ - บ้านบึง",item: 1,vname: "1นจ-5016 กรุงเทพมหานคร",vlicense: "1นจ-5016",provincename: "กรุงเทพมหานคร",driverfullname: "อิงคปกรณ์ 094-283-6403",phone: "094-283-6403",mobile: "0942836403",linename: "",lineimage: "",nickname: "",drivername: "วิทยา",surname: "อิงคปกรณ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 80,compid: 1,routeid: 32,shipid: 0,vehicleid: 16,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายชลบุรี - บางพระ",item: 1,vname: "พ-7655 กรุงเทพมหานคร",vlicense: "พ-7655",provincename: "กรุงเทพมหานคร",driverfullname: "โนนกงกลาง 081-283-0061",phone: "081-283-0061",mobile: "0812830061",linename: "",lineimage: "",nickname: "",drivername: "ณรงค์",surname: "โนนกงกลาง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 90,compid: 1,routeid: 33,shipid: 0,vehicleid: 88,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายชลบุรี - ไร่กล้วย - สวนเสือ",item: 1,vname: "33-5994 กรุงเทพมหานคร",vlicense: "33-5994",provincename: "กรุงเทพมหานคร",driverfullname: "พุ่มเกศรี 064-463-6682",phone: "064-463-6682",mobile: "0644636682",linename: "",lineimage: "",nickname: "",drivername: "สนธยา",surname: "พุ่มเกศรี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 46,compid: 1,routeid: 34,shipid: 0,vehicleid: 63,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายบึงทอง - เขาขยาย",item: 1,vname: "30-2938 ชลบุรี",vlicense: "30-2938",provincename: "ชลบุรี",driverfullname: "สุปัญญา 094-514-1456",phone: "094-514-1456",mobile: "0945141456",linename: "",lineimage: "",nickname: "",drivername: "บุญจันทร์",surname: "สุปัญญา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 71,compid: 1,routeid: 35,shipid: 0,vehicleid: 40,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายปลวกแดง - ตลาดล่าง",item: 1,vname: "30-1167 ระยอง",vlicense: "30-1167",provincename: "ระยอง",driverfullname: "สุขเย็น 094-351-5935",phone: "094-351-5935",mobile: "0943515935",linename: "",lineimage: "",nickname: "",drivername: "กิตติเดช",surname: "สุขเย็น",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 69,compid: 1,routeid: 36,shipid: 0,vehicleid: 21,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายปลวกแดง - วังตาผิน",item: 1,vname: "1นฉ-807 กรุงเทพมหานคร",vlicense: "1นฉ-807",provincename: "กรุงเทพมหานคร",driverfullname: "พุกเนียม 091-823-7158",phone: "091-823-7158",mobile: "0918237158",linename: "",lineimage: "",nickname: "",drivername: "ขรรค์ชัย",surname: "พุกเนียม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 45,compid: 1,routeid: 38,shipid: 0,vehicleid: 20,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายพัทยา (บางละมุง)",item: 1,vname: "1นฆ-483 กรุงเทพมหานคร",vlicense: "1นฆ-483",provincename: "กรุงเทพมหานคร",driverfullname: "วัลภูมิ 087-483-0301",phone: "087-483-0301",mobile: "0874830301",linename: "",lineimage: "",nickname: "",drivername: "สรัช",surname: "วัลภูมิ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 57,compid: 1,routeid: 39,shipid: 0,vehicleid: 12,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายพัทยา (เคหะ-แหลมฉบัง-หนองคล้า)",item: 1,vname: "1นค-8621 กรุงเทพมหานคร",vlicense: "1นค-8621",provincename: "กรุงเทพมหานคร",driverfullname: "ทองตรีพันธ์ 085-047-9024",phone: "085-047-9024",mobile: "0850479024",linename: "",lineimage: "",nickname: "",drivername: "เดโช",surname: "ทองตรีพันธ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 15,compid: 1,routeid: 40,shipid: 0,vehicleid: 9,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายพันเสด็จนอก - เสาสูง",item: 1,vname: "1นก-4183 กรุงเทพมหานคร",vlicense: "1นก-4183",provincename: "กรุงเทพมหานคร",driverfullname: "ชึรัมย์ 085-633-9506",phone: "085-633-9506",mobile: "0856339506",linename: "",lineimage: "",nickname: "",drivername: "ชอบ",surname: "ชึรัมย์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 9,compid: 1,routeid: 41,shipid: 0,vehicleid: 4,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายพันเสด็จใน",item: 1,vname: "1นก-4746 กรุงเทพมหานคร",vlicense: "1นก-4746",provincename: "กรุงเทพมหานคร",driverfullname: "ชัยประสิทธิ์ 089-685-6770",phone: "089-685-6770",mobile: "0896856770",linename: "",lineimage: "",nickname: "",drivername: "สงัด",surname: "ชัยประสิทธิ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 7,compid: 1,routeid: 42,shipid: 0,vehicleid: 5,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายมาบยางพร 1",item: 1,vname: "30-1594 ระยอง",vlicense: "30-1594",provincename: "ระยอง",driverfullname: "พลเสน 061-517-1914",phone: "061-517-1914",mobile: "0615171914",linename: "",lineimage: "",nickname: "",drivername: "ธวัชชัย",surname: "พลเสน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 43,compid: 1,routeid: 43,shipid: 0,vehicleid: 22,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายมาบยางพร 1",item: 2,vname: "นข-6597 บุรีรัมย์",vlicense: "นข-6597",provincename: "บุรีรัมย์",driverfullname: "มณีศรี 080-393-5161",phone: "080-393-5161",mobile: "0803935161",linename: "",lineimage: "",nickname: "",drivername: "ปิยะพงษ์",surname: "มณีศรี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 31,provincecode: "บร",round: 0,planid: 47,compid: 1,routeid: 43,shipid: 0,vehicleid: 79,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายมาบยางพร 2 ",item: 1,vname: "1นก-4098 กรุงเทพมหานคร",vlicense: "1นก-4098",provincename: "กรุงเทพมหานคร",driverfullname: "แจ้งจันทร์ 084-168-1944",phone: "084-168-1944",mobile: "0841681944",linename: "",lineimage: "",nickname: "",drivername: "สุระเดช",surname: "แจ้งจันทร์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 89,compid: 1,routeid: 44,shipid: 0,vehicleid: 3,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายมาบยางพร 2 ",item: 2,vname: "1นข-549 กรุงเทพมหานคร",vlicense: "1นข-549",provincename: "กรุงเทพมหานคร",driverfullname: "สีสันงาม 092-707-2838",phone: "092-707-2838",mobile: "0927072838",linename: "",lineimage: "",nickname: "",drivername: "กิตติศักดิ์",surname: "สีสันงาม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 66,compid: 1,routeid: 44,shipid: 0,vehicleid: 6,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง 1  บ้านค่าย - ปากแพรก",item: 1,vname: "นค-847 ระยอง",vlicense: "นค-847",provincename: "ระยอง",driverfullname: "เขียวสด 064-550-4545",phone: "064-550-4545",mobile: "0645504545",linename: "",lineimage: "",nickname: "",drivername: "ชอบชัย",surname: "เขียวสด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 83,compid: 1,routeid: 46,shipid: 0,vehicleid: 83,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง 2  รพ.กรุงเทพระยอง - มาบข่า ",item: 1,vname: "1นจ-9039 กรุงเทพมหานคร",vlicense: "1นจ-9039",provincename: "กรุงเทพมหานคร",driverfullname: "บุบผารัง 061-484-4995",phone: "061-484-4995",mobile: "0614844995",linename: "",lineimage: "",nickname: "",drivername: "จรัญ",surname: "บุบผารัง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 38,compid: 1,routeid: 47,shipid: 0,vehicleid: 18,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง 3  เซ็นทรัลระยอง-นิคมพัฒนา",item: 1,vname: "ก-4495 พระนครศรีอยุธยา",vlicense: "ก-4495",provincename: "พระนครศรีอยุธยา",driverfullname: "วงศ์สง่า 062-307-6423",phone: "062-307-6423",mobile: "0623076423",linename: "",lineimage: "",nickname: "",drivername: "ถนอม",surname: "วงศ์สง่า",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 67,provincecode: "อย",round: 0,planid: 54,compid: 1,routeid: 48,shipid: 0,vehicleid: 74,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง 4  ระยอง - แม่น้ำคู้ ",item: 1,vname: "1นค-7310 กรุงเทพมหานคร",vlicense: "1นค-7310",provincename: "กรุงเทพมหานคร",driverfullname: "คล้ายแสง 097-928-7851",phone: "097-928-7851",mobile: "0979287851",linename: "",lineimage: "",nickname: "",drivername: "พิชัย",surname: "คล้ายแสง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 5,compid: 1,routeid: 49,shipid: 0,vehicleid: 8,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง 4  ระยอง - แม่น้ำคู้ ",item: 2,vname: "พ-7655 กรุงเทพมหานคร",vlicense: "พ-7655",provincename: "กรุงเทพมหานคร",driverfullname: "โนนกงกลาง 081-283-0061",phone: "081-283-0061",mobile: "0812830061",linename: "",lineimage: "",nickname: "",drivername: "ณรงค์",surname: "โนนกงกลาง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 90,compid: 1,routeid: 49,shipid: 0,vehicleid: 88,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายศรีราชา - เก้ากิโล - อ่าวอุดม",item: 1,vname: " นง-9638 ชลบุรี",vlicense: " นง-9638",provincename: "ชลบุรี",driverfullname: "มหาธิโคตร  090-269-4410",phone: " 090-269-4410",mobile: " 0902694410",linename: "",lineimage: "",nickname: "",drivername: "สนอง",surname: "มหาธิโคตร",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 49,compid: 1,routeid: 51,shipid: 0,vehicleid: 69,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายสัตหีบ",item: 1,vname: "นจ-1068 ชลบุรี",vlicense: "นจ-1068",provincename: "ชลบุรี",driverfullname: "กองคำสุก 062-210-5690",phone: "062-210-5690",mobile: "0622105690",linename: "",lineimage: "",nickname: "",drivername: "สิทธิศักดิ์",surname: "กองคำสุก",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 4,compid: 1,routeid: 53,shipid: 0,vehicleid: 86,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายหนองก้างปลา - เชโก้",item: 1,vname: "30-2512 ชลบุรี",vlicense: "30-2512",provincename: "ชลบุรี",driverfullname: "บุ่งหวาย 061-665-8808",phone: "061-665-8808",mobile: "0616658808",linename: "",lineimage: "",nickname: "",drivername: "ชาตี",surname: "บุ่งหวาย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 39,compid: 1,routeid: 54,shipid: 0,vehicleid: 35,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายห้วยปราบ - สะพานสี่",item: 1,vname: "30-2936 ชลบุรี",vlicense: "30-2936",provincename: "ชลบุรี",driverfullname: "ตุลา 082-541-5986",phone: "082-541-5986",mobile: "0825415986",linename: "",lineimage: "",nickname: "",drivername: "ศราวุฒิ",surname: "ตุลา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 13,compid: 1,routeid: 57,shipid: 0,vehicleid: 39,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายห้วยปราบ - สะพานสี่",item: 2,vname: "30-2943 ชลบุรี",vlicense: "30-2943",provincename: "ชลบุรี",driverfullname: "แก้วเกตุ 092-563-5217",phone: "092-563-5217",mobile: "0925635217",linename: "",lineimage: "",nickname: "",drivername: "ณัฐพงษ์",surname: "แก้วเกตุ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 88,compid: 1,routeid: 57,shipid: 0,vehicleid: 43,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายอีสเทิร์น",item: 1,vname: "ก-4274 ชลบุรี",vlicense: "ก-4274",provincename: "ชลบุรี",driverfullname: "อาจสมดี 061-689-2910",phone: "061-689-2910",mobile: "0616892910",linename: "",lineimage: "",nickname: "",drivername: "สมบัติ",surname: "อาจสมดี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 78,compid: 1,routeid: 58,shipid: 0,vehicleid: 73,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายเขาน้อย - วังแขยง",item: 1,vname: "นข-9681 ระยอง",vlicense: "นข-9681",provincename: "ระยอง",driverfullname: "กลิ่นวิเศษ 080-572-1993",phone: "080-572-1993",mobile: "0805721993",linename: "",lineimage: "",nickname: "",drivername: "ปราการ",surname: "กลิ่นวิเศษ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 3,compid: 1,routeid: 60,shipid: 0,vehicleid: 80,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายไทยออยล์ - เครือสหพัฒน์",item: 1,vname: "ก-4274 ชลบุรี",vlicense: "ก-4274",provincename: "ชลบุรี",driverfullname: "อาจสมดี 061-689-2910",phone: "061-689-2910",mobile: "0616892910",linename: "",lineimage: "",nickname: "",drivername: "สมบัติ",surname: "อาจสมดี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 78,compid: 1,routeid: 62,shipid: 0,vehicleid: 73,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "Adient (โรงใหญ่)",shipname: "กะเช้า",roundname: "รับ",routename: "สายไทยออยล์ - เครือสหพัฒน์",item: 2,vname: "ก-8611 สมุทรปราการ",vlicense: "ก-8611",provincename: "สมุทรปราการ",driverfullname: "พรมงาม 094-838-6849",phone: "094-838-6849",mobile: "0948386849",linename: "",lineimage: "",nickname: "",drivername: "เกียรติชัย",surname: "พรมงาม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 11,provincecode: "สป",round: 0,planid: 41,compid: 1,routeid: 62,shipid: 0,vehicleid: 75,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ชลบุรี",item: 1,vname: "30-6289 ชลบุรี",vlicense: "30-6289",provincename: "ชลบุรี",driverfullname: "นาย ณัทพล เนวิลัย",phone: "065-6479493",mobile: "0656479493",linename: "",lineimage: "",nickname: "",drivername: "ณัทพล",surname: "เนวิลัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 22,compid: 2,routeid: 1,shipid: 0,vehicleid: 55,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "บึงทอง",item: 1,vname: "30-2939 ชลบุรี",vlicense: "30-2939",provincename: "ชลบุรี",driverfullname: "นาย ชนะพันธ์ ยศจังหรีด",phone: "084-4637265",mobile: "0844637265",linename: "",lineimage: "",nickname: "",drivername: "ชนะพันธ์",surname: "ยศจังหรีด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 18,compid: 2,routeid: 4,shipid: 0,vehicleid: 41,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "บ้านบึง",item: 1,vname: "30-1826 ระยอง",vlicense: "30-1826",provincename: "ระยอง",driverfullname: "นาย สำเร็จ สุขมูล",phone: "063-3325851",mobile: "0633325851",linename: "",lineimage: "",nickname: "",drivername: "สำเร็จ",surname: "สุขมูล",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 34,compid: 2,routeid: 9,shipid: 0,vehicleid: 27,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ปลวกแดง",item: 1,vname: "30-6129 ชลบุรี",vlicense: "30-6129",provincename: "ชลบุรี",driverfullname: "นาย นพเก้า สิงห์ชัย",phone: "091-8944591",mobile: "0918944591",linename: "",lineimage: "",nickname: "",drivername: "นพเก้า",surname: "สิงห์ชัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 23,compid: 2,routeid: 10,shipid: 0,vehicleid: 52,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ปลวกแดง",item: 2,vname: "30-6378 ชลบุรี",vlicense: "30-6378",provincename: "ชลบุรี",driverfullname: "นาย ประทีป สินชัย",phone: "099-3432462",mobile: "0993432462",linename: "",lineimage: "",nickname: "",drivername: "ประทีป",surname: "สินชัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 25,compid: 2,routeid: 10,shipid: 0,vehicleid: 59,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ปลวกแดง",item: 3,vname: "ฮข-1840 กรุงเทพมหานคร",vlicense: "ฮข-1840",provincename: "กรุงเทพมหานคร",driverfullname: "นาย ศักดิ์ดา พุ่มพวง",phone: "089-4061388",mobile: "0894061388",linename: "",lineimage: "",nickname: "",drivername: "ศักดิ์ดา",surname: "พุ่มพวง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 31,compid: 2,routeid: 10,shipid: 0,vehicleid: 89,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ระยอง",item: 1,vname: "30-1825 ระยอง",vlicense: "30-1825",provincename: "ระยอง",driverfullname: "นาย ณรงค์ คำโมง",phone: "098-5174483",mobile: "0985174483",linename: "",lineimage: "",nickname: "",drivername: "ณรงค์",surname: "คำโมง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 20,compid: 2,routeid: 15,shipid: 0,vehicleid: 26,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ระยอง",item: 2,vname: "30-4279 ชลบุรี",vlicense: "30-4279",provincename: "ชลบุรี",driverfullname: "นาย สรพงศ์ แก้วสว่าง",phone: "096-7315929",mobile: "0967315929",linename: "",lineimage: "",nickname: "",drivername: "สรพงศ์",surname: "แก้วสว่าง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 33,compid: 2,routeid: 15,shipid: 0,vehicleid: 47,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ศรีราชา",item: 1,vname: "30-6276 ชลบุรี",vlicense: "30-6276",provincename: "ชลบุรี",driverfullname: "นาย ณัฐธนนท์ น้อยเชียงคูณ",phone: "087-6560889",mobile: "0876560889",linename: "",lineimage: "",nickname: "",drivername: "ณัฐธนนท์",surname: "น้อยเชียงคูณ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 21,compid: 2,routeid: 23,shipid: 0,vehicleid: 54,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ศรีราชา",item: 2,vname: "30-6295 ชลบุรี",vlicense: "30-6295",provincename: "ชลบุรี",driverfullname: "นาย จิตรเจริญ จันตุลัง",phone: "095-1159397",mobile: "0951159397",linename: "",lineimage: "",nickname: "",drivername: "จิตรเจริญ",surname: "จันตุลัง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 17,compid: 2,routeid: 23,shipid: 0,vehicleid: 57,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "ศรีราชา",item: 3,vname: "30-6374 ชลบุรี",vlicense: "30-6374",provincename: "ชลบุรี",driverfullname: "นาย วิษณุกรณ์ วงษ์นอก",phone: "061-4295429",mobile: "0614295429",linename: "",lineimage: "",nickname: "",drivername: "วิษณุกรณ์",surname: "วงษ์นอก",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 29,compid: 2,routeid: 23,shipid: 0,vehicleid: 58,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "สะพานสี่",item: 1,vname: "30-2917 ชลบุรี",vlicense: "30-2917",provincename: "ชลบุรี",driverfullname: "นาย ประสิทธิ์ รอดมาลัย",phone: "082-5966591",mobile: "0825966591",linename: "",lineimage: "",nickname: "",drivername: "ประสิทธิ์",surname: "รอดมาลัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 26,compid: 2,routeid: 25,shipid: 0,vehicleid: 36,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "สัตหีบ",item: 1,vname: "30-6291 ชลบุรี",vlicense: "30-6291",provincename: "ชลบุรี",driverfullname: "นาย เตียง โพธิขาว",phone: "065-9283807",mobile: "0659283807",linename: "",lineimage: "",nickname: "",drivername: "เตียง",surname: "โพธิขาว",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 35,compid: 2,routeid: 26,shipid: 0,vehicleid: 56,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "เกาะโพธิ์",item: 1,vname: "30-3797 ชลบุรี",vlicense: "30-3797",provincename: "ชลบุรี",driverfullname: "นาย พนธกร น้อยหลา",phone: "091-0214170",mobile: "0910214170",linename: "",lineimage: "",nickname: "",drivername: "พนธกร",surname: "น้อยหลา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 27,compid: 2,routeid: 70,shipid: 0,vehicleid: 46,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "เขาไม้แก้ว",item: 1,vname: "30-2928 ชลบุรี",vlicense: "30-2928",provincename: "ชลบุรี",driverfullname: "นาย ชวลิต สมประสงค์",phone: "065-4814027",mobile: "0654814027",linename: "",lineimage: "",nickname: "",drivername: "ชวลิต",surname: "สมประสงค์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 19,compid: 2,routeid: 71,shipid: 0,vehicleid: 37,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "เครือ",item: 1,vname: "30-1803 ชลบุรี",vlicense: "30-1803",provincename: "ชลบุรี",driverfullname: "นาย สมชาย รอบคอนครบุรี",phone: "086-6610085",mobile: "0866610085",linename: "",lineimage: "",nickname: "",drivername: "สมชาย",surname: "รอบคอนครบุรี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 32,compid: 2,routeid: 72,shipid: 0,vehicleid: 24,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "เครือ",item: 2,vname: "30-1824 ระยอง",vlicense: "30-1824",provincename: "ระยอง",driverfullname: "นาย บรรเลงศักดิ์ โสมมี",phone: "086-8374634",mobile: "0868374634",linename: "",lineimage: "",nickname: "",drivername: "บรรเลงศักดิ์",surname: "โสมมี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 24,compid: 2,routeid: 72,shipid: 0,vehicleid: 25,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะเช้า",roundname: "รับ",routename: "แหลมฉบัง-เครือ/อ่าวอุดม-บ้านนา",item: 1,vname: "30-3448 ชลบุรี",vlicense: "30-3448",provincename: "ชลบุรี",driverfullname: "นาย ศรายุทธ ประกอบธรรม",phone: "094-4065753",mobile: "0944065753",linename: "",lineimage: "",nickname: "",drivername: "ศรายุทธ",surname: "ประกอบธรรม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 30,compid: 2,routeid: 78,shipid: 0,vehicleid: 45,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ชลบุรี",item: 1,vname: "30-6289 ชลบุรี",vlicense: "30-6289",provincename: "ชลบุรี",driverfullname: "นาย ณัทพล เนวิลัย",phone: "065-6479493",mobile: "0656479493",linename: "",lineimage: "",nickname: "",drivername: "ณัทพล",surname: "เนวิลัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 22,compid: 2,routeid: 1,shipid: 1,vehicleid: 55,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "บึงทอง",item: 1,vname: "30-2939 ชลบุรี",vlicense: "30-2939",provincename: "ชลบุรี",driverfullname: "นาย ชนะพันธ์ ยศจังหรีด",phone: "084-4637265",mobile: "0844637265",linename: "",lineimage: "",nickname: "",drivername: "ชนะพันธ์",surname: "ยศจังหรีด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 18,compid: 2,routeid: 4,shipid: 1,vehicleid: 41,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "บ้านบึง",item: 1,vname: "30-1826 ระยอง",vlicense: "30-1826",provincename: "ระยอง",driverfullname: "นาย สำเร็จ สุขมูล",phone: "063-3325851",mobile: "0633325851",linename: "",lineimage: "",nickname: "",drivername: "สำเร็จ",surname: "สุขมูล",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 34,compid: 2,routeid: 9,shipid: 1,vehicleid: 27,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ปลวกแดง",item: 1,vname: "30-6129 ชลบุรี",vlicense: "30-6129",provincename: "ชลบุรี",driverfullname: "นาย นพเก้า สิงห์ชัย",phone: "091-8944591",mobile: "0918944591",linename: "",lineimage: "",nickname: "",drivername: "นพเก้า",surname: "สิงห์ชัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 23,compid: 2,routeid: 10,shipid: 1,vehicleid: 52,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ปลวกแดง",item: 2,vname: "30-6378 ชลบุรี",vlicense: "30-6378",provincename: "ชลบุรี",driverfullname: "นาย ประทีป สินชัย",phone: "099-3432462",mobile: "0993432462",linename: "",lineimage: "",nickname: "",drivername: "ประทีป",surname: "สินชัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 25,compid: 2,routeid: 10,shipid: 1,vehicleid: 59,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ระยอง",item: 1,vname: "30-1825 ระยอง",vlicense: "30-1825",provincename: "ระยอง",driverfullname: "นาย ณรงค์ คำโมง",phone: "098-5174483",mobile: "0985174483",linename: "",lineimage: "",nickname: "",drivername: "ณรงค์",surname: "คำโมง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 20,compid: 2,routeid: 15,shipid: 1,vehicleid: 26,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ระยอง",item: 2,vname: "30-4279 ชลบุรี",vlicense: "30-4279",provincename: "ชลบุรี",driverfullname: "นาย สรพงศ์ แก้วสว่าง",phone: "096-7315929",mobile: "0967315929",linename: "",lineimage: "",nickname: "",drivername: "สรพงศ์",surname: "แก้วสว่าง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 33,compid: 2,routeid: 15,shipid: 1,vehicleid: 47,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ระยอง",item: 3,vname: "ฮม-296 กรุงเทพมหานคร",vlicense: "ฮม-296",provincename: "กรุงเทพมหานคร",driverfullname: "นาย พิรุณ จันทคาด(ชั่วคราว)",phone: "094-7049925",mobile: "0947049925",linename: "",lineimage: "",nickname: "",drivername: "พิรุณ",surname: "จันทคาด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 28,compid: 2,routeid: 15,shipid: 1,vehicleid: 91,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ศรีราชา",item: 1,vname: "30-6295 ชลบุรี",vlicense: "30-6295",provincename: "ชลบุรี",driverfullname: "นาย จิตรเจริญ จันตุลัง",phone: "095-1159397",mobile: "0951159397",linename: "",lineimage: "",nickname: "",drivername: "จิตรเจริญ",surname: "จันตุลัง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 17,compid: 2,routeid: 23,shipid: 1,vehicleid: 57,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "ศรีราชา",item: 2,vname: "30-6374 ชลบุรี",vlicense: "30-6374",provincename: "ชลบุรี",driverfullname: "นาย วิษณุกรณ์ วงษ์นอก",phone: "061-4295429",mobile: "0614295429",linename: "",lineimage: "",nickname: "",drivername: "วิษณุกรณ์",surname: "วงษ์นอก",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 29,compid: 2,routeid: 23,shipid: 1,vehicleid: 58,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "สะพานสี่",item: 1,vname: "30-2917 ชลบุรี",vlicense: "30-2917",provincename: "ชลบุรี",driverfullname: "นาย ประสิทธิ์ รอดมาลัย",phone: "082-5966591",mobile: "0825966591",linename: "",lineimage: "",nickname: "",drivername: "ประสิทธิ์",surname: "รอดมาลัย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 26,compid: 2,routeid: 25,shipid: 1,vehicleid: 36,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "สัตหีบ",item: 1,vname: "30-6291 ชลบุรี",vlicense: "30-6291",provincename: "ชลบุรี",driverfullname: "นาย เตียง โพธิขาว",phone: "065-9283807",mobile: "0659283807",linename: "",lineimage: "",nickname: "",drivername: "เตียง",surname: "โพธิขาว",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 35,compid: 2,routeid: 26,shipid: 1,vehicleid: 56,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "เกาะโพธิ์",item: 1,vname: "30-3797 ชลบุรี",vlicense: "30-3797",provincename: "ชลบุรี",driverfullname: "นาย พนธกร น้อยหลา",phone: "091-0214170",mobile: "0910214170",linename: "",lineimage: "",nickname: "",drivername: "พนธกร",surname: "น้อยหลา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 27,compid: 2,routeid: 70,shipid: 1,vehicleid: 46,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "เขาไม้แก้ว",item: 1,vname: "30-2928 ชลบุรี",vlicense: "30-2928",provincename: "ชลบุรี",driverfullname: "นาย ชวลิต สมประสงค์",phone: "065-4814027",mobile: "0654814027",linename: "",lineimage: "",nickname: "",drivername: "ชวลิต",surname: "สมประสงค์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 19,compid: 2,routeid: 71,shipid: 1,vehicleid: 37,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "STI",shipname: "กะดึก",roundname: "รับ",routename: "เครือ",item: 1,vname: "30-1824 ระยอง",vlicense: "30-1824",provincename: "ระยอง",driverfullname: "นาย บรรเลงศักดิ์ โสมมี",phone: "086-8374634",mobile: "0868374634",linename: "",lineimage: "",nickname: "",drivername: "บรรเลงศักดิ์",surname: "โสมมี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 24,compid: 2,routeid: 72,shipid: 1,vehicleid: 25,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "บึง (ปั้มเชลล์) ",item: 1,vname: "1นง-9128 กรุงเทพมหานคร",vlicense: "1นง-9128",provincename: "กรุงเทพมหานคร",driverfullname: "อุทัย พิมสาร",phone: "098-450-3869",mobile: "0984503869",linename: "",lineimage: "",nickname: "",drivername: "อุทัย",surname: "พิมสาร",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 81,compid: 3,routeid: 2,shipid: 0,vehicleid: 14,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "บึง(การไฟฟ้า) ",item: 1,vname: "1นฆ-3004 กรุงเทพมหานคร",vlicense: "1นฆ-3004",provincename: "กรุงเทพมหานคร",driverfullname: "ฉลาด พินิจมนตรี",phone: "093-693-0652",mobile: "0936930652",linename: "",lineimage: "",nickname: "",drivername: "ฉลาด",surname: "พินิจมนตรี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 6,compid: 3,routeid: 3,shipid: 0,vehicleid: 10,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "ปากร่วม + สะพานสี่ ",item: 1,vname: "นข-5862 ปราจีนบุรี",vlicense: "นข-5862",provincename: "ปราจีนบุรี",driverfullname: "วีระพล มีขำ",phone: "080-393-5161",mobile: "0803935161",linename: "",lineimage: "",nickname: "",drivername: "วีระพล",surname: "มีขำ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 25,provincecode: "ปจ",round: 0,planid: 59,compid: 3,routeid: 11,shipid: 0,vehicleid: 78,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "พัทยา ",item: 1,vname: "นจ-1024 ชลบุรี",vlicense: "นจ-1024",provincename: "ชลบุรี",driverfullname: "วิษณุ เรืองฉาย",phone: "065-509-7034",mobile: "0655097034",linename: "",lineimage: "",nickname: "",drivername: "วิษณุ",surname: "เรืองฉาย",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 58,compid: 3,routeid: 12,shipid: 0,vehicleid: 85,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "มาบข่า ",item: 1,vname: "นก-1015 กรุงเทพมหานคร",vlicense: "นก-1015",provincename: "กรุงเทพมหานคร",driverfullname: "วรรณะ พาชีชีพ",phone: "098-6595133",mobile: "0986595133",linename: "",lineimage: "",nickname: "",drivername: "วรรณะ",surname: "พาชีชีพ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 55,compid: 3,routeid: 13,shipid: 0,vehicleid: 77,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "มาบยางพร ",item: 1,vname: "1นฆ-3285 กรุงเทพมหานคร",vlicense: "1นฆ-3285",provincename: "กรุงเทพมหานคร",driverfullname: "สุรเชษฐ บัวผัน",phone: "092-876-8838",mobile: "0928768838",linename: "",lineimage: "",nickname: "",drivername: "สุรเชษฐ",surname: "บัวผัน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 73,compid: 3,routeid: 14,shipid: 0,vehicleid: 11,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "วิ่งแทน บึง(การไฟฟ้า) ",item: 1,vname: "นจ-1082 ชลบุรี",vlicense: "นจ-1082",provincename: "ชลบุรี",driverfullname: "รุ่งนภา อุดมถาวรสิน",phone: "082-3946994",mobile: "0823946994",linename: "",lineimage: "",nickname: "",drivername: "รุ่งนภา",surname: "อุดมถาวรสิน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 53,compid: 3,routeid: 18,shipid: 0,vehicleid: 87,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "วิ่งแทน สายมาบข่า",item: 1,vname: "ฮฐ-2154 กรุงเทพมหานคร",vlicense: "ฮฐ-2154",provincename: "กรุงเทพมหานคร",driverfullname: "รัตนภรณ์ ปลอดแก้ว",phone: "065-0397232",mobile: "0650397232",linename: "",lineimage: "",nickname: "",drivername: "รัตนภรณ์",surname: "ปลอดแก้ว",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 51,compid: 3,routeid: 19,shipid: 0,vehicleid: 90,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "วิ่งแทน ห้วยปราบ ",item: 1,vname: "ก-2919 ระยอง",vlicense: "ก-2919",provincename: "ระยอง",driverfullname: "กฤษตฤณ กิตติพงศ์วิวัฒน์",phone: "099-3563222",mobile: "0993563222",linename: "",lineimage: "",nickname: "",drivername: "กฤษตฤณ",surname: "กิตติพงศ์วิวัฒน์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 2,compid: 3,routeid: 20,shipid: 0,vehicleid: 72,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "วิ่งแทน ไร่กล้วย",item: 1,vname: "1-นจ-7399 กรุงเทพมหานคร",vlicense: "1-นจ-7399",provincename: "กรุงเทพมหานคร",driverfullname: "สมเกียรติ บุญชอบ",phone: "095-0744112",mobile: "0950744112",linename: "",lineimage: "",nickname: "",drivername: "สมเกียรติ",surname: "บุญชอบ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 64,compid: 3,routeid: 21,shipid: 0,vehicleid: 2,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "วิ่งแทน ไลฟ์ซิตี้ปาร์ค ",item: 1,vname: "นข-9917 กรุงเทพมหานคร",vlicense: "นข-9917",provincename: "กรุงเทพมหานคร",driverfullname: "สมหมาย เทพวรส",phone: "099-1528061",mobile: "0991528061",linename: "",lineimage: "",nickname: "",drivername: "สมหมาย",surname: "เทพวรส",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 63,compid: 3,routeid: 22,shipid: 0,vehicleid: 81,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "หนองมน",item: 1,vname: "1-นข-8976 กรุงเทพมหานคร",vlicense: "1-นข-8976",provincename: "กรุงเทพมหานคร",driverfullname: "มนตรี ใจอดทน",phone: "093-695-9166",mobile: "0936959166",linename: "",lineimage: "",nickname: "",drivername: "มนตรี",surname: "ใจอดทน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 48,compid: 3,routeid: 64,shipid: 0,vehicleid: 1,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "หนองยายบู่ ",item: 1,vname: "1นข-8775 กรุงเทพมหานคร",vlicense: "1นข-8775",provincename: "กรุงเทพมหานคร",driverfullname: "เสกสรร เมมารี",phone: "081-723-8679",mobile: "0817238679",linename: "",lineimage: "",nickname: "",drivername: "เสกสรร",surname: "เมมารี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 86,compid: 3,routeid: 66,shipid: 0,vehicleid: 7,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "ห้วยปราบ ",item: 1,vname: "30-2070 ระยอง",vlicense: "30-2070",provincename: "ระยอง",driverfullname: "เด่นดวง ปากกาบุตร",phone: "087-5574628",mobile: "0875574628",linename: "",lineimage: "",nickname: "",drivername: "เด่นดวง",surname: "ปากกาบุตร",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 84,compid: 3,routeid: 67,shipid: 0,vehicleid: 28,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "ฮาร์เบอร์มอลล์ + เครือสหพัฒน์ ",item: 1,vname: "นง-8132 ชลบุรี",vlicense: "นง-8132",provincename: "ชลบุรี",driverfullname: "ชาญชัย คำพินิจ",phone: "087-747-8124",mobile: "0877478124",linename: "",lineimage: "",nickname: "",drivername: "ชาญชัย",surname: "คำพินิจ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 8,compid: 3,routeid: 69,shipid: 0,vehicleid: 84,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "โป่งสะเก็ด + อีสเทิร์น ",item: 1,vname: "1นจ-9670 กรุงเทพมหานคร",vlicense: "1นจ-9670",provincename: "กรุงเทพมหานคร",driverfullname: "ทนัด จิตหาญ",phone: "080-602-6239",mobile: "0806026239",linename: "",lineimage: "",nickname: "",drivername: "ทนัด",surname: "จิตหาญ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 14,compid: 3,routeid: 79,shipid: 0,vehicleid: 19,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "ไร่กล้วย ",item: 1,vname: "1นจ-4435 กรุงเทพมหานคร",vlicense: "1นจ-4435",provincename: "กรุงเทพมหานคร",driverfullname: "กรวิชญ์ ขำนอก",phone: "097-1076196",mobile: "0971076196",linename: "",lineimage: "",nickname: "",drivername: "กรวิชญ์",surname: "ขำนอก",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 1,compid: 3,routeid: 80,shipid: 0,vehicleid: 15,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "คอลัมน์",shipname: "กะเช้า",roundname: "รับ",routename: "ไลฟ์ซิตี้ปาร์ค ",item: 1,vname: "ฮร-9373 กรุงเทพมหานคร",vlicense: "ฮร-9373",provincename: "กรุงเทพมหานคร",driverfullname: "สุรพล ทองชุม",phone: "098-189-1546",mobile: "0981891546",linename: "",lineimage: "",nickname: "",drivername: "สุรพล",surname: "ทองชุม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 72,compid: 3,routeid: 81,shipid: 0,vehicleid: 92,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "บึงทอง  3",item: 1,vname: "30-4437 ชลบุรี",vlicense: "30-4437",provincename: "ชลบุรี",driverfullname: "อรุณ หำศิริ",phone: "062-9911570",mobile: "0629911570",linename: "",lineimage: "",nickname: "",drivername: "อรุณ",surname: "หำศิริ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 77,compid: 4,routeid: 5,shipid: 0,vehicleid: 48,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "บึงทอง 1",item: 1,vname: "33-7572 กรุงเทพมหานคร",vlicense: "33-7572",provincename: "กรุงเทพมหานคร",driverfullname: "ศักรินทร์ ชื่นกมล",phone: "094-9592812",mobile: "0949592812",linename: "",lineimage: "",nickname: "",drivername: "ศักรินทร์",surname: "ชื่นกมล",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 60,compid: 4,routeid: 6,shipid: 0,vehicleid: 64,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "บึงทอง 2",item: 1,vname: "30-2941 ชลบุรี",vlicense: "30-2941",provincename: "ชลบุรี",driverfullname: "ประกาศ ผาพรม",phone: "081-4792382",mobile: "0814792382",linename: "",lineimage: "",nickname: "",drivername: "ประกาศ",surname: "ผาพรม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 40,compid: 4,routeid: 7,shipid: 0,vehicleid: 42,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "บึงทอง 4",item: 1,vname: "33-7618 กรุงเทพมหานคร",vlicense: "33-7618",provincename: "กรุงเทพมหานคร",driverfullname: "อนันท์  คำดำ",phone: "089-2457429",mobile: "0892457429",linename: "",lineimage: "",nickname: "",drivername: "อนันท์",surname: "คำดำ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 75,compid: 4,routeid: 8,shipid: 0,vehicleid: 65,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "ลีโอ-ซอยสุพรรณ 1",item: 1,vname: "30-6917 ชลบุรี",vlicense: "30-6917",provincename: "ชลบุรี",driverfullname: "สมศักดิ์ พิมพ์สอน",phone: "064-7179950",mobile: "0647179950",linename: "",lineimage: "",nickname: "",drivername: "สมศักดิ์",surname: "พิมพ์สอน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 62,compid: 4,routeid: 16,shipid: 0,vehicleid: 62,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "ลีโอ-ซอยสุพรรณ 2",item: 1,vname: "36-0092 สระบุรี ",vlicense: "36-0092",provincename: "สระบุรี",driverfullname: "วันชัย  สุวรรณโน",phone: "098-4564234",mobile: "0984564234",linename: "",lineimage: "",nickname: "",drivername: "วันชัย",surname: "สุวรรณโน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 19,provincecode: "สบ",round: 0,planid: 56,compid: 4,routeid: 17,shipid: 0,vehicleid: 66,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "ศรีราชา-เก้ากิโล",item: 1,vname: "36-0344 ชลบุรี",vlicense: "36-0344",provincename: "ชลบุรี",driverfullname: "พิเชษฐ์ ทัพอินทร์",phone: "081-4449525",mobile: "0814449525",linename: "",lineimage: "",nickname: "",drivername: "พิเชษฐ์",surname: "ทัพอินทร์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 44,compid: 4,routeid: 24,shipid: 0,vehicleid: 67,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สาย มาบยางพร",item: 1,vname: "30-2297 ระยอง",vlicense: "30-2297",provincename: "ระยอง",driverfullname: "อภิชาติ  เกิดบ้านเป้า",phone: "062-3963668",mobile: "0623963668",linename: "",lineimage: "",nickname: "",drivername: "อภิชาติ",surname: "เกิดบ้านเป้า",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 76,compid: 4,routeid: 27,shipid: 0,vehicleid: 30,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สาย วังแขยง",item: 1,vname: "30-2396  ระยอง ",vlicense: "30-2396",provincename: "ระยอง",driverfullname: "เทพ  จันทรลูน",phone: "062-4590932",mobile: "0624590932",linename: "",lineimage: "",nickname: "",drivername: "เทพ",surname: "จันทรลูน",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 85,compid: 4,routeid: 28,shipid: 0,vehicleid: 33,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สาย อ่าวดุดม ",item: 1,vname: "30-2306 ระยอง ",vlicense: "30-2306",provincename: "ระยอง",driverfullname: "เอกพงษ์ หุมอาจ",phone: "081-4359261",mobile: "0814359261",linename: "",lineimage: "",nickname: "",drivername: "เอกพงษ์",surname: "หุมอาจ",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 87,compid: 4,routeid: 29,shipid: 0,vehicleid: 32,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายปลวกแดง - มาบยางพร",item: 1,vname: "ก 5922 สมุทรปราการ",vlicense: "ก-5922",provincename: "สมุทรปราการ",driverfullname: "นุกูล  จันทรโกมล",phone: "091-7466225",mobile: "0917466225",linename: "",lineimage: "",nickname: "",drivername: "นุกูล",surname: "จันทรโกมล",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 11,provincecode: "สป",round: 0,planid: 36,compid: 4,routeid: 37,shipid: 0,vehicleid: 70,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายระยอง",item: 1,vname: "30-2467 ระยอง",vlicense: "30-2467",provincename: "ระยอง",driverfullname: "สุกฤษฏ์  สมาณสินธ์",phone: "063-5494939",mobile: "0635494939",linename: "",lineimage: "",nickname: "",drivername: "สุกฤษฏ์",surname: "สมาณสินธ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 67,compid: 4,routeid: 45,shipid: 0,vehicleid: 34,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายวังตาผิน ",item: 1,vname: "30-2296 ระยอง",vlicense: "30-2296",provincename: "ระยอง",driverfullname: "ณัฐศักดิ์  เสียงดัง",phone: "061-4793484",mobile: "0614793484",linename: "",lineimage: "",nickname: "",drivername: "ณัฐศักดิ์",surname: "เสียงดัง",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 12,compid: 4,routeid: 50,shipid: 0,vehicleid: 29,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายสวนเสือ ",item: 1,vname: "30-6192 ชลบุรี ",vlicense: "30-6192",provincename: "ชลบุรี",driverfullname: "เกษม  บุตรพรม",phone: "095-8085275",mobile: "0958085275",linename: "",lineimage: "",nickname: "",drivername: "เกษม",surname: "บุตรพรม",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 82,compid: 4,routeid: 52,shipid: 0,vehicleid: 53,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายหนองคล้า",item: 1,vname: "30-1753 ชลบุรี",vlicense: "30-1753",provincename: "ชลบุรี",driverfullname: "พล นพเทา",phone: "063-660-6050",mobile: "0636606050",linename: "",lineimage: "",nickname: "",drivername: "พล",surname: "นพเทา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 42,compid: 4,routeid: 55,shipid: 0,vehicleid: 23,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายหนองยายบู่",item: 1,vname: "30-6752 ชลบุรี",vlicense: "30-6752",provincename: "ชลบุรี",driverfullname: "ณัฐพงษ์  อาจฤทธิ์",phone: "095-2530152",mobile: "0952530152",linename: "",lineimage: "",nickname: "",drivername: "ณัฐพงษ์",surname: "อาจฤทธิ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 10,compid: 4,routeid: 56,shipid: 0,vehicleid: 60,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายอีสเทิร์น",item: 1,vname: "1นจ-7748 กรุงเทพมหานคร",vlicense: "1นจ-7748",provincename: "กรุงเทพมหานคร",driverfullname: "รัตนา  ขันตี",phone: "098-4913510",mobile: "0984913510",linename: "",lineimage: "",nickname: "",drivername: "รัตนา",surname: "ขันตี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 52,compid: 4,routeid: 58,shipid: 0,vehicleid: 17,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายเคหะ",item: 1,vname: "30-5630 ชลบุรี",vlicense: "30-5630",provincename: "ชลบุรี",driverfullname: "โยธา  ศรีปัญญา",phone: "087-9555890",mobile: "0879555890",linename: "",lineimage: "",nickname: "",drivername: "โยธา",surname: "ศรีปัญญา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 91,compid: 4,routeid: 61,shipid: 0,vehicleid: 51,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "สายไร่กล้วย",item: 1,vname: "30-6827 ชลบุรี",vlicense: "30-6827",provincename: "ชลบุรี",driverfullname: "มัชฌิมา  บัวบุตร",phone: "084-9574819",mobile: "0849574819",linename: "",lineimage: "",nickname: "",drivername: "มัชฌิมา",surname: "บัวบุตร",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 50,compid: 4,routeid: 63,shipid: 0,vehicleid: 61,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "หนองมน",item: 1,vname: "36-0347 ชลบุรี",vlicense: "36-0347",provincename: "ชลบุรี",driverfullname: "สงวนศักดิ์ บุตรวารินทร์",phone: "086-8381123",mobile: "0868381123",linename: "",lineimage: "",nickname: "",drivername: "สงวนศักดิ์",surname: "บุตรวารินทร์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 61,compid: 4,routeid: 64,shipid: 0,vehicleid: 68,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "ห้วยปราบ - สะพานสี่",item: 1,vname: "30-2945 ชลบุรี ",vlicense: "30-2945",provincename: "ชลบุรี",driverfullname: "ณัฐพล แซ่เล้า",phone: "062-8861694",mobile: "0628861694",linename: "",lineimage: "",nickname: "",drivername: "ณัฐพล",surname: "แซ่เล้า",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 11,compid: 4,routeid: 68,shipid: 0,vehicleid: 44,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "เครือสหพัฒน์ 1",item: 1,vname: "30-5187 ชลบุรี",vlicense: "30-5187",provincename: "ชลบุรี",driverfullname: "สุทัศ  ว่องไว",phone: "082-0505762",mobile: "0820505762",linename: "",lineimage: "",nickname: "",drivername: "สุทัศ",surname: "ว่องไว",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 70,compid: 4,routeid: 73,shipid: 0,vehicleid: 49,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "เครือสหพัฒน์ 2",item: 1,vname: "30-5188 ชลบุรี ",vlicense: "30-5188",provincename: "ชลบุรี",driverfullname: "อำนาจ  พระนา",phone: "096-8827729",mobile: "0968827729",linename: "",lineimage: "",nickname: "",drivername: "อำนาจ",surname: "พระนา",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 79,compid: 4,routeid: 74,shipid: 0,vehicleid: 50,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "เครือสหพัฒน์ 3",item: 1,vname: "30-2932 ชลบุรี",vlicense: "30-2932",provincename: "ชลบุรี",driverfullname: "ไพรินทร์ ไกรสิทธิ์",phone: "062-6106810",mobile: "0626106810",linename: "",lineimage: "",nickname: "",drivername: "ไพรินทร์",surname: "ไกรสิทธิ์",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 20,provincecode: "ชบ",round: 0,planid: 92,compid: 4,routeid: 75,shipid: 0,vehicleid: 38,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "แม่น้ำคู้ 1",item: 1,vname: "30-2300  ระยอง ",vlicense: "30-2300",provincename: "ระยอง",driverfullname: "บุญส่ง อันภักดี",phone: "082-8572630",mobile: "0828572630",linename: "",lineimage: "",nickname: "",drivername: "บุญส่ง",surname: "อันภักดี",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 21,provincecode: "รย",round: 0,planid: 37,compid: 4,routeid: 76,shipid: 0,vehicleid: 31,vtypename: "ไม่ระบุ",transtatus: 1},
      {company: "เจเทค",shipname: "กะเช้า",roundname: "รับ",routename: "แม่น้ำคู้ 2 ",item: 1,vname: "1นฆ-7052 กรุงเทพมหานคร",vlicense: "1นฆ-7052",provincename: "กรุงเทพมหานคร",driverfullname: "ธวัชชัย โมมขุนทด",phone: "083-6892898",mobile: "0836892898",linename: "",lineimage: "",nickname: "",drivername: "ธวัชชัย",surname: "โมมขุนทด",dlicensname: "ไม่ระบุ",dlicense: "",dlicensetype: 0,province: 81,provincecode: "กท",round: 0,planid: 16,compid: 4,routeid: 77,shipid: 0,vehicleid: 13,vtypename: "ไม่ระบุ",transtatus: 1}
    ]
    "SELECT company,shipname,roundname,routename,item,vname,vehicle.license as vlicense,provincename,\n" +
    "driver.driverfullname,phone,mobile,linename,lineimage,nickname,\n" +
    "driver.drivername,driver.surname,dlicensname,\n" +
    "driver.license as dlicense,driver.licensetype as dlicensetype,\n" +
    "province,provincecode,round,\n" +
    "planmaster.driverid\n" +
    "planid,planmaster.compid,routeid,shipid,\n" +
    "vehicleid,vtypename,planmaster.transtatus\n" +
    "FROM planmaster\n" +
    "INNER JOIN routeline ON planmaster.routeid = routeline.id\n" +
    "INNER JOIN customer ON planmaster.compid = customer.id\n" +
    "INNER JOIN vehicle ON planmaster.vehicleid = vehicle.id\n" +
    "INNER JOIN driver ON planmaster.driverid = driver.id\n" +
    "LEFT JOIN (SELECT id,th as roundname FROM statustext WHERE tbname = 'roundid') as r ON planmaster.round = r.id\n" +
    "LEFT JOIN (SELECT id,th as shipname FROM statustext WHERE tbname = 'shipid') as s ON planmaster.shipid = s.id\n" +
    "LEFT JOIN (SELECT id,th as dlicensname FROM statustext WHERE tbname = 'driverlicensetype') as dl ON driver.licensetype = dl.id\n" +
    "LEFT JOIN (SELECT id,th as vtypename FROM statustext WHERE tbname = 'vtype') as vt ON vehicle.vtype = vt.id\n" +
    "ORDER BY company,shipid,round,routename,item"
  }

}